# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1104199c6c3febd66c6ddd50979e95041766fdee279e470e8a0f36ef8d0d06174e73421904ff2a0deec50dbfd1a9143e1ddf6791d80ab7f12ac57c6319bfc9ac

test:
  secret_key_base: 7ff97e82286a4006bebf0b9452504f2d9d418f5131971dd154c1f4372c8450e454986bb993844bc1119b4bc799fc9f1c8f2e8cfd330b7a7489a5209ee67f541d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
